package projetsoa.rest.com;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public interface ischool {
	public etu getetu(String email,String pass);
	public etu getetu(int id);
	public int ajouteretu(etu e);
	public prof getprof(int id);
	public prof getprof(String email,String pass);
	public List<annonce> listeanounce();
	public List<annonce> listeanouncep(int id);
	public int inscrirenannonce(int ida,int ide);
	public int quitterannonce(int ida,int ide);
	public int checkinscrir(int ida,int ide);
	public List<annonce> monannonce(int ide);
	public annonce getannonce(int ida);
	public List<annonce> classeannonce(String classe,  String niveau, String filiere);
	public List<annonce> classeannonce(String classe,  String niveau);
	public int supprimerannonce(int ida);
	public int ajouterannonce(annonce a);
	public int modifierannonce(annonce a);
	public List<etu> listetuannonce(int id);
	public int ajouterabscence(int ida,int ide);
	public int getpayement(int ida,int ide);
	public List<etu> listetu();
	public Date getdate(int ide , int ida);
	public List<prof> listprof();
	public List<annonce> listannonce();
	public int modiferetu(etu e);
	public int supprimeretu(int ide);
	public int modifierprof(prof p);
	public List<classe> listeclasse();
	public List<String> listschool(String classe);
	public List<String> listesc();
	public List<String> listniveau(String classe,  String niveau);
	public List listfiliere(String classe,  String niveau, String filiere);
	public int supprimerclasse(int idc);
	public classe getclasse(int idc);
	public int ajouterclasse(classe c);
	public int supprimerprof(int idp);
	public int ajouterprof(prof p);
	public int modifierclasse(classe c);
	public int setpaiment(int ide ,int ida);
	public void setpaimentne(int ide ,int ida);
	public int nombre_jour(int ide,int ida);
	public int checkcne(String cne);
	public admine getadmin(String email,String pass);
	public admine getadmin(int id);
	public List<abscence> listeabscence();
	public int supprimerabscence(int id);
	public int checkpass(String pass,String email);
	public int checketu(String pass,String email);
	public int nb_etudiants();
	public int nb_professeur();
	public int total_prix();
	public int changepassetu(String pass, int ide);
	public int changepassad(String pass, int ida);
	public int changepassprof(String pass, int idp);
}
